### PR TITLE
1.6.3 release

### PR DESCRIPTION
**Pull request by Raatty**

### CODE REVIEW

**Comment by Raatty** [comment]
apart from requiring beta run time it seems to work fine...

**Comment by Raatty** [comment]
switched to freedesktop sdk beta because apparently they releasing new version  next week and seems to work fine after adding libsecret

**Comment by VaiTon** [comment]
@Raatty any blockers for this PR? The flatpak is ATM not working.

**Comment by Raatty** [comment]
> @Raatty any blockers for this PR? The flatpak isn't starting ATM.

Yup it currently requires a runtime from flathub beta

**Pull request merged**
